### ISSUE TITLE
Allow change search params

### ISSUE THREAD

**Issue by raulsh** [turbot/steampipe-plugin-slack#39]
By default search results are paginated:
https://github.com/slack-go/slack/blob/93fe17cfad827ebb34316c683f29377c9be910e3/search.go#L9-L14

And in this implementation params are not allowed to be configured by users:
https://github.com/turbot/steampipe-plugin-slack/blob/main/slack/table_slack_search.go#L46

The problem with this is that we can't get more than 20 results in a single query.  Maybe the pagination could be managed through "LIMIT" or by plugin config.

**Comment by cbruno10** [comment]
@raulsh Pagination support has been added to v0.7.0, if you encounter any issues using this version, please let us know!

**Comment by raulsh** [comment]
@cbruno10 thanks!
