### ISSUE TITLE
Any `select * from slack_` results in `requires hydrate data` error

### ISSUE THREAD

**Issue by securitygeneration** [turbot/steampipe-plugin-slack#46]
**Describe the bug**
Any `select * from slack_` results in an error like:

```
Error: table 'slack_user' column 'workspace_domain' requires hydrate data from getCommonColumns, which failed with error missing_scope.
 (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
v0.16.4

**Plugin version (`steampipe plugin list`)**
Slack v0.9.0

**To reproduce**
`select * from slack_user`

**Expected behavior**
The full list of users and their fields (although this is just based on the example provided)

**Comment by misraved** [comment]
Thanks @securitygeneration for raising the issue and welcome to Steampipe 👍 .

Relevant slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1665043011644439

**Comment by misraved** [comment]
As per the slack conversation, the issue was resolved by adding the correct permission scope.
